nipoppy/nipoppy

workflow/proc_pipe/mriqc/scripts/eval_mriqc_results_sge.sh, workflow/proc_pipe/mriqc/scripts/run_mriqc_sge.sh
=> added mriqc scripts

workflow/proc_pipe/mriqc/Dockerfile_mriqc_patch, workflow/proc_pipe/mriqc/README.md
=> added readme and dockerfile

workflow/proc_pipe/scripts/eval_mriqc_results.py
=> Update function name

.github/workflows/validation.yml, CITATION.cff
- add a citation.cff file to the repo with metadata about contributors
- add a workflow to make sure the file is valid
=> [MAINT] add citation file and validation workflow

.github/workflows/codespell.yml, extractors/freesurfer/collate_freesurfer_stats.py, extractors/freesurfer/run_FS_utils.py, pyproject.toml, workflow/bids_conv/sample_heuristic.py, workflow/dicom_org/utils.py
so upcoming release (#103) is shining with correctness! ;-)
=> codespell: config, workflow and typos fixed

.github/workflows/update_dataset_repos.yml
Mainly `mr_proc` -> `nipoppy` + deleted `nipoppy_nimhans`
Closes #124.
=> Update repo names in GitHub actions for updating dataset forks

.github/workflows/codespell.yml
=> Do not run Codespell on `*.ipynb` files

.github/workflows/check_changed_files.yml, .github/workflows/update_dataset_repos.yml
Closes #150.
Also did some light refactoring of `update_dataset_repos.yml`.
=> Do not check changed files when syncing with downstream forks

.github/workflows/codespell.yml, pyproject.toml
=> Make Codespell ignore HTML files and PPMI-specific file

.github/workflows/codespell.yml
=> Do not trigger Codespell on push events

nipoppy/workflow/dicom_org/check_dicom_status.py, nipoppy/workflow/dicom_org/sample_dicom_dir_func.py
=> add `session_id` to `participant_id_to_dicom_dir()`

.gitmodules, nipoppy/trackers/tractoflow_tracker.py, nipoppy/workflow/proc_pipe/tractoflow/run_tractoflow.py, nipoppy/workflow/proc_pipe/tractoflow/sample_bids_filter.json
I checked the parsing with the bval/bvec files. This was ready to go, but I've improved the comments / logging so it's clear what's going on.
There was a bug in the max lmax check, but it wasn't impacting anything.
=> update to tractoflow run for bval parsing

nipoppy/workflow/proc_pipe/tractoflow/run_tractoflow.py
- fixed parsing issues for some T1 images - just dropped `sag` filter.
- updated logging for more verbose reporting / traceback of what files get selected as forward / reverse phase encodings
-  clarified the language of interpreting `lmax` selection to be more clear
=> Quick fix for tractoflow data parsing missing valid T1s

nipoppy/trackers/run_tracker.py, nipoppy/workflow/make_doughnut.py
=> use doughnut file to get BIDS ID in `run_tracker.py` (create if needed)

nipoppy/sample_global_configs.json
=> add "ses-" prefix to `sample_global_configs.json`

nipoppy/workflow/proc_pipe/tractoflow/run_tractoflow.py
This should clean up completed runs of tractoflow as part of the processing. 
Be sure to do a smaller test in the first batch - it _should_ be working, but tf is a real challenge to test conclusively.
=> Remove symlinks from tractoflow output

nipoppy/extractors/fmriprep/run_FC.py
Add a few checks to see if the needed files and dirs exist.
=> add checks for dir exist

nipoppy_cli/pyproject.toml
just released FIDS to pypi so this can now go through
=> [MAINT] use official fids

nipoppy_cli/docs/source/schemas/index.rst, nipoppy_cli/nipoppy/config/__init__.py, nipoppy_cli/nipoppy/config/main.py, nipoppy_cli/nipoppy/config/pipeline.py, nipoppy_cli/nipoppy/config/pipeline_step.py, nipoppy_cli/nipoppy/data/examples/sample_global_config-all_pipelines.json, nipoppy_cli/nipoppy/data/examples/sample_global_config-latest_pipelines.json, nipoppy_cli/nipoppy/data/layouts/layout-default.json, nipoppy_cli/nipoppy/workflows/bids_conversion.py, nipoppy_cli/nipoppy/workflows/pipeline.py, nipoppy_cli/tests/conftest.py, nipoppy_cli/tests/test_config_main.py, nipoppy_cli/tests/test_config_pipeline.py, nipoppy_cli/tests/test_config_pipeline_step.py, nipoppy_cli/tests/test_layout.py, nipoppy_cli/tests/test_workflow_bids_conversion.py, nipoppy_cli/tests/test_workflow_pipeline.py
- Closes #268 
- Closes #271 
- Closes #272
- This one involved a refactor of `PipelineStepConfig` and `PipelineConfig` that touches several files, but the changes are not too big
=> [FIX] Fix doughnut path and other bugs

nipoppy_cli/nipoppy/workflows/pipeline.py, nipoppy_cli/tests/test_workflow_pipeline.py, nipoppy_cli/tests/test_workflow_runner.py
=> [FIX] Fix `nipoppy run` creating empty PyBIDS database on second (and later) loop iteration

nipoppy_cli/nipoppy/tabular/bagel.py, nipoppy_cli/tests/test_tabular_bagel.py
=> [FIX] Add `pipeline_starttime` to bagel file

.flake8, .pre-commit-config.yaml, CITATION.cff, nipoppy_cli/nipoppy/cli/parser.py, nipoppy_cli/nipoppy/config/container.py, nipoppy_cli/nipoppy/config/main.py, nipoppy_cli/nipoppy/env.py, nipoppy_cli/nipoppy/layout.py, nipoppy_cli/nipoppy/tabular/base.py, nipoppy_cli/nipoppy/tabular/doughnut.py, nipoppy_cli/nipoppy/workflows/base.py, nipoppy_cli/nipoppy/workflows/dataset_init.py, nipoppy_cli/nipoppy/workflows/dicom_reorg.py, nipoppy_cli/nipoppy/workflows/doughnut.py, nipoppy_cli/nipoppy/workflows/pipeline.py, nipoppy_cli/nipoppy/workflows/runner.py, nipoppy_cli/nipoppy/workflows/tracker.py, nipoppy_cli/tests/conftest.py, nipoppy_cli/tests/test_tabular_doughnut.py, tests/conftest.py, tests/test_workflow_mriqc.py
- update pre-commit config
- apply all pre-commit hooks
=> [MAINT] change linting config and apply pre-commit

.github/workflows/label_new_issue.yml, .github/workflows/project_automation.yml, .github/workflows/stale.yml
- Closes #331
- 2 new workflows
- Not 100% sure that the project automation one will work once merged but on my fork it worked (see for example https://github.com/michellewang/nipoppy/issues/5)
- Need to discuss if we still want to use the status labels
=> [ENH] Add GitHub Project automation

.github/workflows/project_automation.yml
=> [FIX] Add changes erased by force-push

.github/workflows/label_new_issue.yml
- Closes #343
- 
For bug fixes:
=> [BUG] Fix `label_new_issue.yml` failing 

nipoppy/config/pipeline.py, nipoppy/config/pipeline_step.py, nipoppy/data/examples/sample_global_config-all_pipelines.json, nipoppy/data/examples/sample_global_config-latest_pipelines.json, nipoppy/tabular/bagel.py, nipoppy/utils.py, nipoppy/workflows/pipeline.py, tests/test_config_pipeline.py, tests/test_config_pipeline_step.py, tests/test_utils.py, tests/test_workflow_pipeline.py
- Closes #257
- New configuration field for pipeline steps: `"ANALYSIS_LEVEL"`, which can be one of:
- `"participant_session"`(default): same behaviour as before, looping over every participant-session pair (given some constraints)
- `"participant"`: only looping over participants
- `"session"`: only looping over sessions
- `"group"`: only 1 iteration
- Note: This introduces the possibility of the Boutiques invocation having `None` instead of a participant ID (for example) if the user did not specify the invocation correctly
- Note 2: Currently the trackers are still at the pipeline level, not the pipeline _step_ level because that would make things break with the dashboard, though I think tracking at the step level makes sense. We should probably …
=> [ENH] Add `"ANALYSIS_LEVEL"` field to pipeline step config to allow group-level processing

docs/source/contributing.md, docs/source/installation.md
- Closes #357 
- Heavily based on [Neurobagel contributing docs](https://neurobagel.org/contributing/CONTRIBUTING/)
- Preview: https://nipoppy--375.org.readthedocs.build/en/375/contributing.html
For bug fixes:
=> [DOC] Update contribution guide

nipoppy/tabular/doughnut.py, nipoppy/workflows/dicom_reorg.py, tests/conftest.py, tests/data/doughnut1.tsv, tests/data/doughnut2.tsv, tests/data/doughnut_invalid2.tsv, tests/test_tabular_doughnut.py, tests/test_workflow_bids_conversion.py, tests/test_workflow_dicom_reorg.py, tests/test_workflow_doughnut.py, tests/test_workflow_runner.py, tests/test_workflow_tracker.py
- Closes #394
- Rename `in_raw_imaging` -> `in_pre_reorg`
- Rename `in_sourcedata` -> `in_post_reorg`
- Open to other names if anyone has a strong opinion
For bug fixes:
=> [ENH] Rename doughnut columns

docs/source/user_guide/inserts/custom_dicom_reorg-after.txt, docs/source/user_guide/inserts/custom_dicom_reorg-before.txt, docs/source/user_guide/inserts/default_dicom_reorg-after.txt, docs/source/user_guide/inserts/default_dicom_reorg-before.txt
- Closes #403
- Updated `scratch/raw_imaging` -> `sourcedata/imaging/pre_reorg`
- Updated `sourcedata` -> `sourcedata/imaging/post_reorg`
For bug fixes:
=> [DOC] Update file trees in user guide page for DICOM reorg

docs/source/conf.py
- Closes #431
- Add GitHub icon that links to code repo
- Docs preview: https://nipoppy--434.org.readthedocs.build/en/434/
For bug fixes:
=> [DOC] Add icon/link to GitHub repo in docs footer

pyproject.toml
- Closes none
PyBIDS 0.18.0 seems to have a bug, which is causing the test to fail. See https://github.com/bids-standard/pybids/issues/1107
For bug fixes:
=> [MAINT] Exclude PyBIDS version 0.18.0 from dependencies

docs/source/conf.py
- Closes #458
- Add Plausible (hosted by Neurobagel)
- This *should* only be applied on actual releases (i.e. not in local builds or on PR preview builds), but this is not 100% tested. Commenting out some of the conditions makes this work in the PR build
For bug fixes:
=> [DOC] Add Plausible analytics

nipoppy/data/examples/sample_pipelines/heudiconv-0.12.2/descriptor.json, nipoppy/data/examples/sample_pipelines/heudiconv-0.12.2/invocation-convert.json, nipoppy/data/examples/sample_pipelines/heudiconv-0.12.2/invocation-prepare.json
- Closes #470
- 
For bug fixes:
=> [BUG] Update Heudiconv descriptor and invocation files

nipoppy/data/examples/sample_global_config-all_pipelines.json, nipoppy/data/examples/sample_global_config-latest_pipelines.json, nipoppy/data/examples/sample_pipelines/dcm2bids-3.1.0/descriptor-dcm2bids_helper.json, nipoppy/data/examples/sample_pipelines/dcm2bids-3.1.0/invocation-prepare.json
- Closes #493
- 
For bug fixes:
=> [BUG] Fix bug in invocation file for `dcm2bids`'s `prepare` step

.github/release.yml, .github/workflows/update_citation_cff.yml, .github/workflows/validate_citation_cff.yml, CITATION.cff
- Closes #510
- Workflow will:
- get latest release version (from GitHub)
- update `CITATION.cff`
- open a PR
- PR author will be `nipoppy-bot`
For bug fixes:
=> [MAINT] Add GitHub Actions workflow to automatically update `CITATION.cff` version after release

docs/source/cli_reference/index.rst, docs/source/cli_reference/status.rst, nipoppy/workflows/__init__.py
- Closes #468
- 
For bug fixes:
=> [DOC] Add a CLI reference page for `nipoppy status`

nipoppy/workflows/pipeline.py, pyproject.toml, tests/test_workflow_pipeline.py
=> [ENH] Remove special handling of SGE jobs (PySQA >= 0.2.4)

nipoppy/data/hpc/job_script_template.sh, nipoppy/workflows/pipeline.py, tests/test_workflow_pipeline.py
- Closes none
- 
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--589.org.readthedocs.build/en/589/
=> [FIX] Remove `-cwd` from SGE template script

nipoppy/cli.py, nipoppy/workflows/dataset_status.py, nipoppy/workflows/pipeline_store/search.py, nipoppy/zenodo_api.py, tests/test_cli.py, tests/test_workflow_pipeline_store_search.py, tests/test_zenodo_api.py
- Closes #568
- <img width="1029" alt="Screenshot 2025-04-15 at 5 23 52 PM" src="https://github.com/user-attachments/assets/3abd5e23-fac9-49a5-b9c6-eb058f40b021" />
- <img width="901" alt="Screenshot 2025-04-15 at 5 25 02 PM" src="https://github.com/user-attachments/assets/e417cf22-3d3c-4b60-9f69-a21d2601fc81" />
- <img width="926" alt="Screenshot 2025-04-15 at 5 26 37 PM" src="https://github.com/user-attachments/assets/9e757890-f13e-48d4-a9c0-9dc33fcde9d7" />
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--599.org.readthedocs.build/en/599/
=> [ENH] Implement `nipoppy pipeline search`

pyproject.toml
- Closes #
- 
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--730.org.readthedocs.build/en/730/
=> [MAINT] Enable colors in GH actions.

nipoppy/utils/html.py, nipoppy/workflows/pipeline_store/search.py, tests/unit/utils/test_bids.py, tests/unit/utils/test_html.py, tests/unit/utils/test_utils.py, tests/unit/workflows/pipeline_store/test_search.py
- Closes #710 
- Addresses some of #603 (add clickable link to Zenodo record)
- Remove specific HTML tags from description
- Add link to Zenodo record
- Search for "all" records matching query, then only show a subset based on `--size` option
- Otherwise there is no way to search by "most downloaded"
- Change table column text justification
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--781.org.readthedocs.build/en/781/
=> [ENH] Make minor improvements to `nipoppy pipeline search` output table
