.github/workflows/update_dataset_repos.yml

Fix bug in PR #70 where the newly created PRs aren't merged because they haven't been approved, even if the PAT is from an admin (see [here](https://github.com/pascalgn/automerge-action/issues/200)). Now the GitHub Actions workflow uses a second Personal Access Token to approve the PR. Then, like before, it will try to merge the PR. If the PR can't be merged (for example due to merge conflicts), the run will fail. 
Notes:
* I have re-enabled the "Do not allow bypassing the above settings" branch protection rule again since it seems we can't bypass approval requirements through the GitHub API anyway.
* Sometimes the PR can't be merged even though there are no conflicts. This is because GitHub doesn't always accurately compute if a PR can be merged (see …

Fix GitHub Actions for updating dataset repos

---

setup.cfg

pybids is called but wasn't part of the installation.
I'm using it to parse inputs to try and automate decisions about how / what files are used.
This shouldn't conflict / is a worthwhile dependency.

added pybids as dependency

---

sample_global_configs.json

- Add `"VISITS"` key
- Add `"TABULAR"` key with subsections `"DEMOGRAPHICS"` and `"ASSESSMENTS"` (matches tree structure)
- Should be used to generate phenotypic data bagels (and maybe the manifest)
Closes #100.

Update sample global configs

---

nipoppy/trackers/bagel_schema.json
nipoppy/trackers/run_tracker.py

Closes #180, closes #174, closes #97 (except for the `--check-for-update` flag)
With a minor bug fix that made the script write new bagel files even if they didn't change from the previous version.
Some notes:
- Added more logic to handle the fMRIPrep 20.2.7 results being in `output/fmriprep` instead of just `output`. So @nikhil153 depending on your setup for QPN/NIMHANS we might need to put things back into an `fmriprep` subdirectory
- I have a personal preference for using the version name without a preceding `v`, which is how I have coded the Boutiques thing to do for now. This PR makes the tracker compatible with the current Boutiques runner outputs. So this will break things with older runscripts unless we rename the version directories (e.g. `v20.2.7` -> `20.2.7`). @nikhil153 let me …

Update trackers to use manifest and handle tar archives

---

nipoppy/workflow/proc_pipe/tractoflow/run_tractoflow.py
nipoppy/workflow/utils.py

Closes #197 (see there for list of issues fixed in this PR).
Fixed path issue needed to run Tractoflow successfully with my PPMI setup on Compute Canada which involves symlinks.
Other fixes are mostly minor except for the logic error when determining `x`/`y`(/`z`) phase encoding direction.

Fix Tractoflow runscript bugs

---

nipoppy/workflow/proc_pipe/fmriprep/run_fmriprep.py
nipoppy/workflow/proc_pipe/mriqc/run_mriqc.py

Closes #193.
- If the `bids_db_dir` does not exist, write warning in log and create it
- There was a note saying that `run_nipoppy.py` created those directories, but since we don't require that users run `run_nipoppy.py`, we should handle (within the runscript) the case where the `bids_db_dir` does not exist
- @nikhil153 `bids_db_dir` is not an argument in `run_fmriprep.run()`, but it is in `run_mriqc.run()`. It is unclear to me what users should provide if they provide a custom path, and it will break things if that path is not already accessible inside the container. So I suggest doing what we do in `run_fmriprep.run()` and just not have it as an argument that the user sets (i.e., always use `<DATASET_ROOT>/proc/<bids_db_mriqc>`)
- Add `--cleanenv` argument to the Singularity `run` call …

Fix MRIQC (and fMRIPrep) runscript bugs 

---

nipoppy/workflow/proc_pipe/tractoflow/run_tractoflow.py

Closes #201 (see issue for descriptions of the 3 minor bugs).
Also changed the Singularity command so that the bound path is `derivatives/tractoflow/<VERSION>` (resolved), instead of just `derivatives` because I am using symlinks pointing to other places on disk where I have more storage.

Fix TractoFlow symlink bugs

---

nipoppy_cli/docs/source/installation.md

I cannot remember if this is a powershell or just another type of shell issue, but I know that fr some users you need to type:
`pip install -e '.[dev]'`

[DOC] make install command more robust

---

.flake8
.github/workflows/run_tests_new.yml
nipoppy_cli/docs/source/conf.py
nipoppy_cli/nipoppy/config/container.py
nipoppy_cli/nipoppy/config/main.py
nipoppy_cli/nipoppy/config/pipeline.py
nipoppy_cli/nipoppy/layout.py
nipoppy_cli/nipoppy/logger.py
nipoppy_cli/nipoppy/tabular/base.py
nipoppy_cli/nipoppy/tabular/doughnut.py
nipoppy_cli/nipoppy/tabular/manifest.py
nipoppy_cli/nipoppy/utils.py
nipoppy_cli/nipoppy/workflows/base.py
nipoppy_cli/nipoppy/workflows/bids_conversion.py
nipoppy_cli/nipoppy/workflows/dataset_init.py
nipoppy_cli/nipoppy/workflows/dicom_reorg.py
nipoppy_cli/nipoppy/workflows/doughnut.py
nipoppy_cli/nipoppy/workflows/pipeline.py
nipoppy_cli/nipoppy/workflows/runner.py
nipoppy_cli/nipoppy/workflows/tracker.py
nipoppy_cli/pyproject.toml
nipoppy_cli/tests/conftest.py
nipoppy_cli/tests/test_tabular_base.py
nipoppy_cli/tests/test_tabular_doughnut.py
nipoppy_cli/tests/test_utils.py
nipoppy_cli/tests/test_workflow_pipeline.py

Closes #236
- Update CI workflow for tests
- Update `pyproject.toml` to 
- Add `from __future__ import annotations` to files that use `|` for `typing.Union` (only available in Python >= 3.10 otherwise)
- Use `from typing_extensions import Self` instead of `from typing import Self` (only available in Python >= 3.11) 
- Combine `str | pathlib.Path` into `StrOrPathLike` typevar

[FIX] Make sure Python >=3.9 is supported

---

.gitignore
nipoppy_cli/docs/source/conf.py
nipoppy_cli/nipoppy/cli/parser.py
nipoppy_cli/nipoppy/cli/run.py
nipoppy_cli/nipoppy/config/container.py
nipoppy_cli/nipoppy/config/main.py
nipoppy_cli/nipoppy/env.py
nipoppy_cli/nipoppy/layout.py
nipoppy_cli/nipoppy/logger.py
nipoppy_cli/nipoppy/tabular/base.py
nipoppy_cli/nipoppy/tabular/doughnut.py
nipoppy_cli/nipoppy/utils.py
nipoppy_cli/nipoppy/workflows/base.py
nipoppy_cli/nipoppy/workflows/bids_conversion.py
nipoppy_cli/nipoppy/workflows/dataset_init.py
nipoppy_cli/nipoppy/workflows/dicom_reorg.py
nipoppy_cli/nipoppy/workflows/doughnut.py
nipoppy_cli/nipoppy/workflows/pipeline.py
nipoppy_cli/nipoppy/workflows/runner.py
nipoppy_cli/nipoppy/workflows/tracker.py
nipoppy_cli/pyproject.toml
nipoppy_cli/tests/conftest.py
nipoppy_cli/tests/test_tabular_doughnut.py
nipoppy_cli/tests/test_workflow_pipeline.py

- Some config variable where imported from other module, by consequence importing bulky packages (e.g. pandas). I moved the needed variables to a new `nipoppy_cli/nipoppy/env.py`.
-  I moved the workflow imports from the top of the file so they are only called when the needed. 
With these changes, the imports take significantly less time.
fixes #279

[ENH] [REFACTOR] imports to improve performance of the cli.

---

nipoppy_cli/docs/source/conf.py
nipoppy_cli/nipoppy/cli/parser.py
nipoppy_cli/tests/test_parser.py

- Closes #318
- Closes #309
- remove warning in doc build by ignoring version and cli modules from the doc build
- add a `--version` action to the CLI
- add version to doc
For bug fixes:

[ENH] add version to cli

---

.github/workflows/build_and_publish.yml

So I think (but am not 100% sure) that I messed up the [release workflow file](https://github.com/nipoppy/nipoppy/blob/96bc16237db7b0c9527e9f8ed675396c7550e2be/.github/workflows/build_and_publish.yml#L7) because it restricted runs on pushes to the `main` branch, but from what I can tell the tags are not pushed to `main`. @Remi-Gau is that correct? This is what I am suspecting because I ran the following locally and it didn't seem to trigger the workflow (though the tag showed up on GitHub):
```console
git tag 0.2.0
git push upstream tag 0.2.0
```
So this PR makes the GitHub Actions workflow run on all pushes instead of just pushes to `main`.
Refer to [NumPy Development Guide](https://numpy.org/doc/stable/dev/development_workflow.html#writing-the-commit …

[MAINT] Fix (?) release workflow

---

.github/release.yml
.github/workflows/build_and_publish.yml

- Closes #315 
- 
Create a release template as shown [here](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes)
For bug fixes:

[ENH] add automatic release notes for GitHub.

---

nipoppy_cli/nipoppy/cli/parser.py
nipoppy_cli/nipoppy/cli/run.py
nipoppy_cli/tests/test_parser.py

- Closes #328
- Make existing test more robust (though it does not test subparsers which was the cause of the original error)
- Add new test for subparsers
For bug fixes:

[BUG] Fix error when using invalid verbosity level

---

nipoppy/cli/run.py
nipoppy/env.py
nipoppy/logger.py
pyproject.toml
tests/test_logger.py

- Closes #355
- Exclude `pydicom` version `3.0.0` from dependencies
- Do not propagate Nipoppy loggers to root logger. Otherwise, if the root logger has handlers that print to stdout/stderr, they will be duplicated 
- Note that this is disabled during testing because `pytest` relies on the propagation for the `caplog` fixture
For bug fixes:

[BUG] Fix logging issues

---

docs/source/changelog.rst
docs/source/conf.py
docs/source/index.md
pyproject.toml

- Closes #360
- Add doc dependency `sphinx-github-changelog` and use it to 
- Note: New PAT with `contents` read permissions added to Readthedocs project
- Preview: https://nipoppy--361.org.readthedocs.build/en/361/changelog.html
For bug fixes:

[DOC] Add auto-generated changelog page to docs

---

nipoppy/config/main.py
nipoppy/config/pipeline.py
nipoppy/workflows/base.py
nipoppy/workflows/bids_conversion.py
nipoppy/workflows/pipeline.py
nipoppy/workflows/runner.py
tests/test_config_pipeline.py
tests/test_workflow_pipeline.py
tests/test_workflow_tracker.py

- Closes none
- Extracted from #352 which is too big
- Previously, `BasePipelineStep` objects had a `get_step_config(pipeline_step)` method to get the config for a specific pipeline step and a bunch of getter functions that wrapped around it to get step attributes. This was in workflows because every time we needed to access a field in a pipeline step config, we had to call one of the getters and provide the pipeline step name, which is fixed
- This PR is a refactor that adds a `pipeline_step_config` property to workflow objects, similar to `pipeline_config`
- …

[MAINT] Refactor pipeline step config in workflow classes

---

docs/source/_templates/autoapi/index.rst
docs/source/conf.py
nipoppy/config/boutiques.py
nipoppy/config/container.py
nipoppy/config/main.py
nipoppy/config/pipeline.py
nipoppy/config/pipeline_step.py
pyproject.toml
tests/test_config_container.py

- Closes #364
- Relax version restrictions for the `doc` dependencies
- Update jinja templates to be compatible with latest version of `sphinx-autoapi`
- Also fix redundant class doc sections
- Silence cross-referencing warning
- Required making the `SchemaWithContainerConfig` class private, which I think makes sense anyway. We should probably make more parts of the API private to make the docs less cluttered...
For bug fixes:

[FIX] Support latest version of doc dependencies

---

docs/source/conf.py
nipoppy/config/main.py
nipoppy/workflows/bids_conversion.py
nipoppy/workflows/pipeline.py
tests/test_config_main.py
tests/test_workflow_bids_conversion.py
tests/test_workflow_pipeline.py

- Closes #388
- Needed for eventual PR for #385
- Make `get_pipeline_version` and `get_pipeline_config` in `nipoppy.config.main` take a list of pipelines as input
- Previously they were hardcoded to pool together the config's `BIDS_PIPELINES` and `PROC_PIPELINES`
- Add a `_pipeline_configs` attribute to `BasePipelineWorkflow` which will be used by `check_pipeline_version` and the `pipeline_config` property
For bug fixes:

[BUG] Do not pool BIDS and PROC pipelines together when searching pipeline configs

---

nipoppy/workflows/base.py
tests/test_workflow_base.py

- Closes #409
- Add `extra={'markup': False}` to `BaseWorkflow.run_command` and `BaseWorkflow.log_command` logger calls
For bug fixes:

[FIX] Do not enable markup language processing when logging messages related to subprocesses

---

nipoppy/config/pipeline.py

BIDS and Preprocessing pipeline classes now handle the step validation, making the JSON schema less confusing in the docs.
- Closes #
- 
For bug fixes:

[MAINT] refactor pipeline steps.

---

nipoppy/env.py
nipoppy/tabular/doughnut.py
nipoppy/workflows/dataset_init.py
nipoppy/workflows/pipeline.py
tests/test_tabular_doughnut.py
tests/test_workflow_init.py
tests/test_workflow_pipeline.py

- Closes #171 
- datasets with no session definition will be allowed
- the manifest file will have a fake session name for participants with no session level when starting from a BIDS dataset
- the doughnut file won't exclude participants with no sessions
For bug fixes:

[ENH] Allow BIDS datasets without session level

---

nipoppy/data/examples/sample_pipelines/mriqc-23.1.0/descriptor.json

- Closes none
- Related to previous PR fixing fMRIPrep descriptors #426 
- Rename some input fields in the descriptor so that they match the MRIQC CLI flags. Otherwise, the Boutiques argparse-to-descriptor function takes the `dest` field by default, which can be misleading if there is a hook function used for the argument's `type` field. For example the `--mem` argument for memory can be specified in non-gigabyte units, but calling the input element `--memory_gb` makes that more obscure
For bug fixes:
- ~There is at least one test …

[ENH] Rename some input IDs in MRIQC descriptor

---

nipoppy/workflows/dicom_reorg.py
tests/test_workflow_dicom_reorg.py

- Closes #372 
- Closes #448
- Pass entire filepath (instead of just filename) to `apply_fname_mapping` for more user flexibility
- Resolve source/destination paths to avoid problems with symlinks
- Log symlink/copying operations at `DEBUG` level instead of `INFO`
For bug fixes:

[ENH] Improve `DicomReorgWorkflow` customization flexibility and logging

---

.github/workflows/build_and_publish.yml

- Closes none
- The GitHub release workflow is currently failing because we are using an older version of `sigstore/gh-action-sigstore-python` which uses `v3` of `actions/upload-artifact` and `actions/download-artifact`. This should be fixed by updating the version to `v3.0.0` (latest)
For bug fixes:

[BUG] Update Sigstore action version

---

nipoppy/data/examples/sample_pipelines/fs_stats-0.2.0/invocation.json

- Closes none
- Default paths were wrong
For bug fixes:

[BUG] Fix paths in `fs_stats` extractor default invocation

---

nipoppy/workflows/dataset_init.py
tests/test_workflow_init.py

- Closes #488 
- Allow `nipoppy init` in empty dir.  Only `.DS_STORE` can be present.
For bug fixes:

[BUG] Fix `nipoppy init` in existing dirs.

---

.github/workflows/add_doc_link_to_pr.yaml

- Closes #532
- This CI workflow uses the action https://github.com/readthedocs/actions/tree/v1/preview to add a link to the documentation preview at the end of the PR description whenever a new PR is opened
For bug fixes:

[MAINT] Add CI workflow for Read the docs preview link

---

nipoppy/data/examples/sample_global_config-all_pipelines.json
nipoppy/data/examples/sample_global_config-latest_pipelines.json
nipoppy/data/examples/sample_pipelines/bids-validator-2.0.3/descriptor.json
nipoppy/data/examples/sample_pipelines/bids-validator-2.0.3/invocation.json
tests/test_default_config.py

- Closes #530
- Add config and Boutiques files for the latest [BIDS validator](https://github.com/bids-standard/bids-validator)
- Note that the new BIDS validator is not containerized, but it is run through the `deno` JavaScript runtime, which has a container, so this is what I used
BIDS validator help (for verifying the Boutiques descriptor) message:
For bug fixes:

[ENH] Add `bids-validator` `2.0.3`

---

nipoppy/config/main.py
nipoppy/config/pipeline.py
nipoppy/data/examples/sample_global_config.json
nipoppy/data/examples/sample_pipelines/bids/bidscoin-4.3.2/config.json
nipoppy/data/examples/sample_pipelines/bids/dcm2bids-3.1.0/config.json
nipoppy/data/examples/sample_pipelines/bids/dcm2bids-3.2.0/config.json
nipoppy/data/examples/sample_pipelines/bids/heudiconv-0.12.2/config.json
nipoppy/data/examples/sample_pipelines/extraction/fs_stats-0.2.0/config.json
nipoppy/data/examples/sample_pipelines/extraction/static_FC-0.1.0/config.json
nipoppy/data/examples/sample_pipelines/proc/fmriprep-20.2.7/config.json
nipoppy/data/examples/sample_pipelines/proc/fmriprep-23.1.3/config.json
nipoppy/data/examples/sample_pipelines/proc/fmriprep-24.1.1/config.json
nipoppy/data/examples/sample_pipelines/proc/freesurfer-6.0.1/config.json
nipoppy/data/examples/sample_pipelines/proc/freesurfer-7.3.2/config.json
nipoppy/data/examples/sample_pipelines/proc/mriqc-23.1.0/config.json
nipoppy/data/examples/sample_pipelines/proc/qsiprep-0.23.0/config.json
nipoppy/env.py
nipoppy/workflows/pipeline.py
tests/conftest.py
tests/test_config_main.py
tests/test_config_pipeline.py
tests/test_default_config.py
tests/test_workflow_pipeline.py

- Closes #544
- Add `PIPELINE_VARIABLES` field to the global config
- Refactor existing substitutions into `PIPELINE_VARIABLES` -- for now keep them all in the default config, but eventually only add them when adding a pipeline to a dataset
- `SUBSTITUTIONS` is still there, I don't think we necessarily need to remove it but we can discuss
- Now the pipeline config Pydantic classes have a `PIPELINE_TYPE` field which is used to decide where the pipeline variables should go. Will be useful for knowing where to put files in `nipoppy pipeline install` too

[ENH] Add `PIPELINE_VARIABLES` to global config

---

.github/release.yml

- Closes none
- [Previously](https://github.com/nipoppy/nipoppy/blob/591dd2673d3a6d7a7847f783529aecb8d4257495/.github/release.yml#L5) we had `dependabot[bot]` in the list of excluded authors in `.github/release.yml`, which seems to be wrong since the [latest release notes](https://github.com/nipoppy/nipoppy/releases/tag/0.3.4) include PRs from Dependabot
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--580.org.readthedocs.build/en/580/

[MAINT] Fix dependabot username in `release.yml`

---

nipoppy/cli.py

- Closes #607 
- delete --regenerate flag from rich_click.OPTION_GROUPS in order to show `--regenerate, --force` not twice when running `nipoppy track-curation -h`
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--609.org.readthedocs.build/en/609/

[BUG] delete --regenerate flag from rich_click.OPTION_GROUPS

---

.github/workflows/build_and_publish.yml

- Closes #574
- Make the Nipoppy bot (instead of GitHub Actions) be author of the release, so that other CI workflows can trigger from that release
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--581.org.readthedocs.build/en/581/

[MAINT] Update release workflow to use Nipoppy bot token instead of default token

---

.github/workflows/build_and_publish.yml
nipoppy/cli.py
nipoppy/workflows/pipeline_store/zenodo.py
nipoppy/zenodo_api.py
tests/conftest.py
tests/data/zenodo_password.txt
tests/test_cli.py
tests/test_workflow_zenodo.py
tests/test_zenodo_api.py

- Related #596 
- Confirm before uploading to Zenodo
- Read password from file, to prevent leak (recommend by https://clig.dev/#arguments-and-flags)
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--626.org.readthedocs.build/en/626/

Enhance security and safeguard for Zenodo uploads.

---

nipoppy/cli.py
nipoppy/workflows/base.py
nipoppy/workflows/dataset_init.py
tests/test_workflow_init.py

This PR adds `--force` flag option to the init command. 
This is useful for dirs that are already under version control and have .git or .datalad dirs.
Fixes https://github.com/nipoppy/nipoppy/issues/520
What should the expected behavior be when there are existing files that will collide?
[In this comment](https://github.com/nipoppy/nipoppy/issues/520#issuecomment-3058127939) and in the helptext I added, we would clobber those files, which seems reasonable to me. 
This seems to be the case for all files except for the bids source.  When I run the init --force command twice, I would expect to clobber all files, but instead there is a problem with the bids source files.  
`FileExistsError: [Errno 17] File exists: '/home/austin/devel/sandbox/ds004101' -> '/tmp/nipoppy-force-test/bids'` 
I …

[ENH]: allow forced dataset init on non-empty dirs

---

nipoppy/env.py
nipoppy/workflows/pipeline.py
tests/test_workflow_pipeline.py

- Closes #600
- Change log level from warning to error
- Return non-zero exit code
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--690.org.readthedocs.build/en/690/

[BUG] Exit with non-zero code if no participants/sessions were found when running a pipeline

---

nipoppy/config/container.py
nipoppy/env.py
nipoppy/workflows/bids_conversion.py
nipoppy/workflows/extractor.py
nipoppy/workflows/pipeline.py
nipoppy/workflows/pipeline_store/install.py
nipoppy/workflows/runner.py
pyproject.toml
tests/test_config_container.py
tests/test_workflow_bids_conversion.py
tests/test_workflow_extractor.py
tests/test_workflow_pipeline_store_install.py
tests/test_workflow_runner.py

- Closes #239
- Let `bosh` handle container launching instead of having Nipoppy inject container-specific things in the Boutiques descriptor
- Maintain backward compatibility:
- If the descriptor's `command-line` does contains `[[NIPOPPY_...]]`, maintain legacy behaviour
- Otherwise, pass the container image path and any container options through the `--imagepath` and `--container-opts` options for `bosh exec launch`
- In the global config, if `CONTAINER_CONFIG.COMMAND` is `None`, pass `--no-container` to `bosh exec launch`
For bug fixes:
----
📚 Documentation …

[ENH] Let `bosh` handle container launching

---

docs/source/overview/quickstart/index.md

The dcm2bids version in the examples sometimes was 3.1.0 but we want 3.2.0
For bug fixes:
----
📚 Documentation preview 📚: https://nipoppy--739.org.readthedocs.build/en/739/

fix dcm2bids version in examples
